services:
  # --- FRONTEND ---
  front:
    image: riff.front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api

  # --- BACKEND API ---
  api:
    image: riff.api
    build:
      context: ./backend
      dockerfile: Riff.Api/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__default=Host=db;Port=5432;Database=riff;Username=riff;Password=riff
      - PlaylistService__Url=http://playlist:8080
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__QueueName=riff.api
    extra_hosts:
      - "auth.local.oshideck.app:host-gateway"
      - "riff.local.oshideck.app:host-gateway"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      aspire-dashboard:
        condition: service_started

  # --- PLAYLIST SERVICE ---
  playlist:
    image: riff.playlist
    build:
      context: ./backend
      dockerfile: Riff.PlaylistService/Dockerfile
    restart: always
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__default=Host=db;Port=5432;Database=riff;Username=riff;Password=riff
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__QueueName=riff.playlist
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      aspire-dashboard:
        condition: service_started

  notification:
    image: riff.notification
    build:
      context: ./backend
      dockerfile: Riff.NotificationService/Dockerfile
    restart: always
    ports:
      - "8083:8080"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest
      - RabbitMq__QueueName=riff.notification
    depends_on:
      rabbitmq:
        condition: service_healthy
      aspire-dashboard:
        condition: service_started
  
  identity:
    image: riff.identity
    build:
      context: ./backend
      dockerfile: Riff.Identity/Dockerfile
    restart: always
    ports:
      - "5005:8080"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__default=Host=db;Port=5432;Database=riff;Username=riff;Password=riff
    depends_on:
      db:
        condition: service_healthy

  # --- INFRASTRUCTURE ---
  
  db:
    image: postgres:18
    container_name: riff-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: riff
      POSTGRES_PASSWORD: riff
      POSTGRES_DB: riff
    volumes:
      - riff_pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U riff -d riff"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: riff-rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - riff_rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- OBSERVABILITY ---
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    volumes:
      - riff_grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

#  caddy:
#    image: caddy:alpine
#    container_name: riff-gateway
#    restart: always
#    ports:
#      - "80:80"
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile
#    depends_on:
#      - front
#      - api
#      - notification
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    container_name: aspire-dashboard
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      - "18888:18888" 
      - "4317:18889"

volumes:
  riff_pg_data:
  riff_rabbit_data:
  riff_grafana_data: