services:
  api:
    image: riff.api
    build:
      context: ./backend
      dockerfile: Riff.Api/Dockerfile
  front:
    image: riff.front
    ports:
      - "3000:80"
    build:
      context: ./front
      dockerfile: Dockerfile
  db:
    image: postgres:18
    container_name: riff-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: riff
      POSTGRES_PASSWORD: riff
      POSTGRES_DB: riff
    ports:
      - "5432:5432"
    volumes:
      - riff_pg_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U riff -d riff" ]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: synapse-rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - riff_rabbit_data:/var/lib/rabbitmq
  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    network_mode: host
volumes:
  riff_pg_data:
  riff_rabbit_data: